
export const MOVIE_UPDATE = 'MOVIE_UPDATE';
export const MOVIE_TOWATCH_UPDATE = 'MOVIE_TOWATCH_UPDATE';
export const MOVIE_WACHED = 'MOVIE_WACHED';
export const MOVIE_FILTER_UPDATE = 'MOVIE_FILTER_UPDATE';
export const SEARCH_DATA_UPDATE = 'SEARCH_DATA_UPDATE';
export const MOVIE_GENRE_UPDATE = 'MOVIE_GENRE_UPDATE';
export const MOVIE_DETAILS_UPDATE = 'MOVIE_DETAILS_UPDATE';

export const TYPING = 'TYPING';
export const STRING = 'STRING';
export const SEARCH_BTN = 'SEARCH_BTN';
export const FILTER_BTN = 'FILTER_BTN';
export const LOADER_UPDATE = 'LOADER_UPDATE';
export const NEXT_PAGE_LOADER_UPDATE = 'NEXT_PAGE_LOADER_UPDATE';
export const HOME_PAGE_LOADER_UPDATE = 'HOME_PAGE_LOADER_UPDATE';
export const NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE';
